name: Print workflow #Название workflow
on: workflow_dispatch #Триггер, который будет вызывать workflow

jobs: #Начало секции джобов  
    print_hello: #Название джоба    
       runs-on: windows-latest #Среда выполнения джоба 

       steps: #Начало секции шагов     
           - name: Print hello #Название шага        
             run: echo “Greeting" 
